### ISSUE TITLE
Wrong Node.js version in README.md

### ISSUE THREAD

**Issue by Grsmto** [PolymathNetwork/Polymath-Tests#6]
Hey,
The README.md says `Install NodeJS (v 8.11.3)` but the `package.json` says:
```
"engines": {
        "node": ">=10.8.0"
 },
```

So if you install 8.11.3 you have an error when doing `yarn` as of the rule from the pkg.
I didn't PR because I'm not sure what Node.js version is actually recommended.

**Comment by josepmc** [comment]
I'll update the readme, the version we're using is 10 or higher. There are a few cases where selenium-webdriverjs will close the socket and node will crash instantly in 8.x.
